using System.Linq;
using System.Numerics;
using Robust.Client.Graphics;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface;
using Content.Client.UserInterface.Controls;
using Content.Shared._DV.SmartFridge;

namespace Content.Client._DV.SmartFridge;

// L5 - various renames for conflicts with upstream
public record SmartFridgeListDataDV(EntityUid Representative, SmartFridgeEntry Entry, int Amount) : ListData;

[GenerateTypedNameReferences]
public sealed partial class SmartFridgeMenuDV : FancyWindow
{
    [Dependency] private readonly IEntityManager _entityManager = default!;

    public event Action<GUIBoundKeyEventArgs, ListData>? OnItemSelected;
    public event Action<SmartFridgeListDataDV>? OnRemoveButtonPressed;

    private readonly StyleBoxFlat _styleBox = new() { BackgroundColor = new Color(70, 73, 102) };

    public SmartFridgeMenuDV()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        VendingContents.SearchBar = SearchBar;
        VendingContents.DataFilterCondition += DataFilterCondition;
        VendingContents.GenerateItem += GenerateButton;
        VendingContents.ItemKeyBindDown += (args, data) => OnItemSelected?.Invoke(args, data);
    }

    private bool DataFilterCondition(string filter, ListData data)
    {
        if (data is not SmartFridgeListDataDV entry)
            return false;

        if (string.IsNullOrEmpty(filter))
            return true;

        return entry.Entry.Name.Contains(filter, StringComparison.CurrentCultureIgnoreCase);
    }

    private void GenerateButton(ListData data, ListContainerButton button)
    {
        if (data is not SmartFridgeListDataDV entry)
            return;

        var label = Loc.GetString("smart-fridge-list-item", ("item", entry.Entry.Name), ("amount", entry.Amount));
        var item = new SmartFridgeItemDV(entry.Representative, label);
        item.RemoveButtonPressed += () => OnRemoveButtonPressed?.Invoke(entry);
        button.AddChild(item);

        button.ToolTip = label;
        button.StyleBoxOverride = _styleBox;
    }

    public void Populate(Entity<SmartFridgeDVComponent> ent)
    {
        var listData = new List<ListData>();

        foreach (var item in ent.Comp.Entries)
        {
            if (!ent.Comp.ContainedEntries.TryGetValue(item, out var items) || items.Count == 0)
            {
                listData.Add(new SmartFridgeListDataDV(EntityUid.Invalid, item, 0));
            }
            else
            {
                var representative = _entityManager.GetEntity(items.First());
                listData.Add(new SmartFridgeListDataDV(representative, item, items.Count));
            }
        }

        VendingContents.PopulateList(listData);
    }
}
