using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._DV.SmartFridge;

// L5 - renamed with DV suffix.
// L5 TODO: kill this and replace with upstream

[GenerateTypedNameReferences]
public sealed partial class SmartFridgeItemDV : BoxContainer
{
    public Action? RemoveButtonPressed;

    public SmartFridgeItemDV(EntityUid uid, string text)
    {
        RobustXamlLoader.Load(this);

        EntityView.SetEntity(uid);
        NameLabel.Text = text;
        RemoveButton.OnPressed += _ => RemoveButtonPressed?.Invoke();

        if (uid.IsValid())
            RemoveButton.Visible = false;
    }
}
