[game]
lobbyenabled            = true
lobbyduration           = 300
round_restart_time      = 600
round_end_pacifist      = true
contraband_examine      = false # Doubtful that it's desired at all, and would require going over every item in accordance with SOP
soft_max_players        = 50
showgreentext           = false # focus more on telling a story
secret_weight_prototype = "SecretDeltaV"
role_timers             = false # no time requirements for roles
cryo_sleep_rejoining    = true
hostname_in_titlebar    = true
tabletop_place          = true # Worth the risk.
current_year_offset     = 526 # We've been playing in the 2550s
defaultpreset           = "Greenshift"

[nf14.respawn]
time = 0

[vote]
preset_enabled = true
map_enabled    = true

[whitelist]
enabled = true

[chat]
max_announcement_length = 1000
sign_respects_los       = true
all_can_sign            = false

[ooc]
enable_during_round = true

[ic]
flavor_text      = true
punctuation      = true
name_case        = false
restricted_names = false
id_job_length    = 40

[atmos]
space_wind   = true
grid_impulse = false # this just sends some salvage wrecks flying.

[shuttle]
arrivals                       = false # doesn't work very well in general, and not at all with Outpost
emergency_dock_time            = 360 # an extra 2 minutes over the default
emergency_transit_time_min     = 90
auto_call_time                 = 0 # don't automatically call the shuttle
emergency_early_launch_allowed = true
recall_turning_point           = 0.33

[cargo]
# Departmental-economy-b-gone
allow_primary_cut_adjustment = false

[surgery]
can_operate_on_self = false # mrp...

[rules]
time = 15

[infolinks]
github     = "https://github.com/lagrange14/substations"
website    = "https://lagrange14.com/"
wiki       = "https://lagrange14.com/wiki/Main_Page"
bug_report = "https://github.com/lagrange14/substations/issues/new/choose"

[tips]
tippy_chance = 0.05 # Better with Motes

[tippy]
entity = "Motes" # The best tipster...

[net]
max_connections = 1024
tickrate        = 30

[netres]
limit = 10.0

[admin]
see_own_notes               = true
deadmin_on_join             = false
allow_multi_server_play     = true
admins_count_in_playercount = true
[admin.alert]
min_players_sharing_connection = 2

[ahelp]
admin_prefix         = false
admin_prefix_webhook = false

[server]
rules_file             = "L5Ruleset"

[control]
storage_limit = 2

[discord]
rich_main_icon_id = "l5"

[hub]
hub_urls = "https://hub.playss14.com/"

[auth]
server = "https://auth.playss14.com/"
