- abstract: true
  components:
  - drawdepth: Mobs
    noRot: true
    type: Sprite
  - type: MobCollision
  - type: GravityAffected
  - type: Physics
  - fixtures:
      fix1:
        density: 50
        layer:
        - MobLayer
        mask:
        - MobMask
        shape:
          radius: 0.35
    type: Fixtures
  - type: Clickable
  - type: InteractionOutline
  - context: human
    type: Input
  - type: Actions
  - type: Alerts
  - type: Appearance
  - defaultRotation: 0
    horizontalRotation: 0
    type: RotationVisuals
  - type: DoAfter
  - type: Examiner
  - type: Eye
  - type: ContentEye
  - type: CameraRecoil
  - type: MindContainer
  - active: false
    type: RequireProjectileTarget
  - type: StunVisuals
  - type: AnimatedEmotes
  id: BaseControllable
  save: false
  type: entity
- abstract: true
  components:
  - type: MobCollision
  - bodyType: KinematicController
    type: Physics
  - type: InputMover
  - type: MobMover
  - type: MovementSpeedModifier
  - type: LagCompensation
  id: BaseMob
  parent: BaseControllable
  save: false
  type: entity
- abstract: true
  components:
  - type: Polymorphable
  id: MobPolymorphable
  save: false
  type: entity
- abstract: true
  components:
  - damageContainer: Biological
    type: Damageable
  - thresholds:
    - behaviors:
      - popup: mouth-taste-metal
        popupType: LargeCaution
        targetOnly: true
      trigger:
        damage: 15
        damageType: Radiation
    - behaviors:
      - ""
      trigger:
        damage: 40
        damageType: Radiation
    type: Destructible
  - type: RadiationReceiver
  - type: Stamina
  - type: StunVisuals
  - type: MobState
  - thresholds:
      0: Alive
      100: Critical
      200: Dead
    type: MobThresholds
  - actions:
      Critical:
      - ActionCritSuccumb
      - ActionCritFakeDeath
      - ActionCritLastWords
    type: MobStateActions
  - type: Deathgasp
  - examinableTypes:
    - Blunt
    - Slash
    - Piercing
    - Heat
    - Shock
    - Cold
    - Caustic
    - Asphyxiation
    - Radiation
    type: HealthExaminable
  - damage:
      types:
        Blunt: 5
    soundHit:
      path: /Audio/Effects/hit_kick.ogg
    type: DamageOnHighSpeedImpact
  - type: Pullable
  - lightningExplode: false
    priority: 2
    type: LightningTarget
  - baseDamage: 0.1
    dirtinessThreshold: 100
    inverseDamageCoefficient: 500
    toxinStepLimit: 1
    type: SurgeryContaminable
  - type: LongTermHealth
  id: MobDamageable
  save: false
  type: entity
- abstract: true
  components:
  - type: CombatMode
  - damage:
      groups:
        Brute: 5
    hidden: true
    soundHit:
      collection: MetalThud
    type: MeleeWeapon
  id: MobCombat
  save: false
  type: entity
- abstract: true
  components:
  - type: AtmosExposed
  - coldDamage:
      types:
        Cold: 0.1
    coldDamageThreshold: 0
    currentTemperature: 310.15
    heatDamage:
      types:
        Heat: 1.5
    heatDamageThreshold: 325
    specificHeat: 42
    type: Temperature
  - implicitHeatRegulation: 500
    metabolismHeat: 800
    normalBodyTemperature: 310.15
    radiatedHeat: 100
    shiveringHeatRegulation: 2000
    sweatHeatRegulation: 2000
    thermalRegulationTemperatureThreshold: 2
    type: ThermalRegulator
  - type: MovedByPressure
  id: MobAtmosExposed
  save: false
  type: entity
- abstract: true
  components:
  - implicitHeatRegulation: 250
    metabolismHeat: 800
    normalBodyTemperature: 310.15
    radiatedHeat: 100
    shiveringHeatRegulation: 500
    sweatHeatRegulation: 500
    thermalRegulationTemperatureThreshold: 2
    type: ThermalRegulator
  - coldDamage:
      types:
        Cold: 1
    coldDamageThreshold: 260
    currentTemperature: 310.15
    heatDamage:
      types:
        Heat: 1.5
    heatDamageThreshold: 325
    specificHeat: 42
    type: Temperature
  - damage:
      types:
        Blunt: 0.15
    type: Barotrauma
  id: MobAtmosStandard
  parent: MobAtmosExposed
  type: entity
- abstract: true
  components:
  - canResistFire: true
    damage:
      types:
        Heat: 1.5
    fireSpread: true
    type: Flammable
  - normalState: Generic_mob_burning
    sprite: Mobs/Effects/onfire.rsi
    type: FireVisuals
  id: MobFlammable
  save: false
  type: entity
- abstract: true
  components:
  - type: Internals
  - damage:
      types:
        Asphyxiation: 2
    damageRecovery:
      types:
        Asphyxiation: -1
    type: Respirator
  id: MobRespirator
  save: false
  type: entity
- abstract: true
  components:
  - type: SolutionContainerManager
  - solution: chemicals
    type: InjectableSolution
  - bloodlossDamage:
      types:
        Bloodloss: 0.5
    bloodlossHealDamage:
      types:
        Bloodloss: -1
    type: Bloodstream
  id: MobBloodstream
  save: false
  type: entity
