using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared._DV.MedicalRecords;
using Content.Shared.MedicalScanner;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.HealthAnalyzer.UI;

[GenerateTypedNameReferences]
public sealed partial class HealthAnalyzerWindow : FancyWindow
{
    // Begin DeltaV - Medical Records
    private readonly ButtonGroup _triageStatusGroup = new();
    private readonly Dictionary<TriageStatus, Button> _triageControls = new();

    public event Action<TriageStatus>? OnTriageStatusChanged;
    public event Action? OnClaimPatient;
    // End DeltaV - Medical Records

    public HealthAnalyzerWindow()
    {
        RobustXamlLoader.Load(this);

        // Begin DeltaV - Medical Records
        foreach (var item in Enum.GetValues<TriageStatus>())
        {
            var btn = new Button();
            var ftlKey = item.ToString();
            btn.Group = _triageStatusGroup;
            btn.Text = Loc.GetString($"health-analyzer-window-triage-status-{ftlKey}");
            btn.ToolTip = Loc.GetString($"health-analyzer-window-triage-status-{ftlKey}.ToolTip");
            btn.OnPressed += _ => OnTriageStatusChanged?.Invoke(item);
            btn.AddStyleClass("ButtonSquare");
            StatusBox.AddChild(btn);
            _triageControls[item] = btn;
        }
        StatusBox.Children.First().AddStyleClass("OpenRight");
        StatusBox.Children.First().RemoveStyleClass("ButtonSquare");
        StatusBox.Children.Last().AddStyleClass("OpenLeft");
        StatusBox.Children.Last().RemoveStyleClass("ButtonSquare");
        ClaimButton.OnPressed += _ => OnClaimPatient?.Invoke();
        // End DeltaV - Medical Records
    }

    public void Populate(HealthAnalyzerScannedUserMessage msg)
    {
        // Begin DeltaV - Medical Records
        if (msg.State.MedicalRecord is not {} records)
        {
            TriageControls.Visible = false;
        }
        else
        {
            TriageControls.Visible = true;
            _triageControls[records.Status].Pressed = true;
        }
        // End DeltaV - Medical Records

        HealthAnalyzer.Populate(msg.State);
    }
}
