- type: entity
  name: butterfly orchid bunch
  parent: FoodProduceBase
  id: FoodButterflyOrchid
  description: It looks as if there are many butterflies flying around it. It gives a touch of spring.
  components:
  - type: Clothing
    slots:
    - HEAD
    quickEquip: false
  - type: FlavorProfile
    flavors:
    - honey
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 10
        reagents:
        - ReagentId: Nutriment
          Quantity: 5
        - ReagentId: ButterfliesReagent
          Quantity: 5
  - type: Sprite
    sprite: _Impstation/Objects/Specific/Hydroponics/butterfly_orchid.rsi
    state: produce
  - type: Produce
    seedId: butterflyorchid
  - type: Extractable
    juiceSolution:
      reagents:
      - ReagentId: ButterfliesReagent
        Quantity: 15
  - type: Tag
    tags:
    - Flower

- type: entity
  name: biggerfly orchid bunch
  parent: FoodProduceBase
  id: FoodBiggerflyOrchid
  description: It looks as if there are many butterflies flying around it. They're large.
  components:
  - type: FlavorProfile
    flavors:
    - honey
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 20
        reagents:
        - ReagentId: Nutriment
          Quantity: 10
        - ReagentId: ButterfliesBiggerReagent
          Quantity: 10
  - type: Sprite
    sprite: _Impstation/Objects/Specific/Hydroponics/biggerfly_orchid.rsi
    state: produce
  - type: Produce
    seedId: biggerflyorchid
  - type: Extractable
    juiceSolution:
      reagents:
      - ReagentId: ButterfliesBiggerReagent
        Quantity: 15
  - type: Tag
    tags:
    - Flower

- type: entity
  name: floating flora
  parent: [FoodProduceBase, BaseDeployFoldable]
  id: FoodFloatingFlora
  description: Some say they can be seen flying in migration patterns in the wild..
  components:
  - type: FlavorProfile
    flavors:
      - medicine
  - type: Tag
    tags:
    - Flower
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 12
        reagents:
        - ReagentId: Nutriment
          Quantity: 2
  - type: Produce
    seedId: floatingflora
#  - type: Extractable
#    juiceSolution:
#      reagents:
#      - ReagentId: Uppisium (will be adding at a later date, post apparent status effects change)
#        Quantity: 10
#foldable
  - type: Transform
    noRot: true
  - type: Item
    size: Normal
    heldPrefix: floating_flora_y
  - type: Sprite
    sprite: _Impstation/Objects/Specific/Hydroponics/floating_flora.rsi
    noRot: true
    layers:
    - state: floating_flora_y
      map: ["unfoldedLayer"]
    - state: floating_flora_folded_y
      map: ["foldedLayer"]
      visible: false
    - type: InteractionOutline
  - type: Pullable
#trying to float
  - type: MovementIgnoreGravity # nyoom
    gravityState: true
  - type: Physics
    bodyStatus: InAir
  - type: FloatingVisuals

# flora color variants
- type: entity
  name: floating flora
  parent: [FoodFloatingFlora]
  id: FoodFloatingFloraPink
  components:
  - type: Sprite
    sprite: _Impstation/Objects/Specific/Hydroponics/floating_flora.rsi
    noRot: true
    layers:
    - state: floating_flora_p
      map: ["unfoldedLayer"]
    - state: floating_flora_folded_p
      map: ["foldedLayer"]
      visible: false

- type: entity
  name: floating flora
  parent: [FoodFloatingFlora]
  id: FoodFloatingFloraOrange
  components:
  - type: Sprite
    sprite: _Impstation/Objects/Specific/Hydroponics/floating_flora.rsi
    noRot: true
    layers:
    - state: floating_flora_o
      map: ["unfoldedLayer"]
    - state: floating_flora_folded_o
      map: ["foldedLayer"]
      visible: false

- type: entity
  name: floating flora
  parent: [FoodFloatingFlora]
  id: FoodFloatingFloraBlue
  components:
  - type: Sprite
    sprite: _Impstation/Objects/Specific/Hydroponics/floating_flora.rsi
    noRot: true
    layers:
    - state: floating_flora_b
      map: ["unfoldedLayer"]
    - state: floating_flora_folded_b
      map: ["foldedLayer"]
      visible: false

- type: entity
  name: hops
  parent: FoodProduceBase
  id: FoodHops
  description: Looking to start your own craft brewery, huh? With your own unique twist on the IPA?
  components:
  - type: FlavorProfile
    flavors:
    - beer
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 9
        reagents:
        - ReagentId: Nutriment
          Quantity: 5
        - ReagentId: Vitamin
          Quantity: 4
  - type: Sprite
    sprite: _Impstation/Objects/Specific/Hydroponics/hops.rsi
    state: hops
  - type: Produce
    seedId: hops
  - type: Extractable
    juiceSolution:
      reagents:
      - ReagentId: Beer
        Quantity: 10
  - type: Tag
    tags:
    - Fruit
