- type: entity
  name: pear
  parent: FoodProduceBase
  id: FoodPear
  description: It's peary good.
  components:
  - type: FlavorProfile
    flavors:
    - pear
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 13 # L5 might as well tune this down to match the value I was roughing things off of
        reagents:
        - ReagentId: Nutriment
          Quantity: 8
        - ReagentId: Vitamin
          Quantity: 3
  - type: Sprite
    sprite: _NF/Objects/Specific/Hydroponics/pear.rsi
  - type: Produce
    seedId: pear
  - type: Tag
    tags:
    - Fruit
